import { IconRobot } from "@tabler/icons-react";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Fira_Sans } from "next/font/google";

const firaFont = Fira_Sans({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800"],
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`min-h-screen font-sans text-white ${firaFont.variable} bg-gradient-to-br from-[#1f2733] to-[#1f2838]`}
      >
        {/* <div className="absolute -z-10 h-screen w-screen">
          <Image
            src="/bg-new.png"
            alt="Roses as background"
            fill
            style={{ objectFit: "cover" }}
          />
        </div> */}
        <div className="mx-auto flex justify-around bg-gradient-to-b from-[#1f2733] to-[#1f2838] px-4 py-6 text-xl shadow shadow-pink-500">
          <Link
            href="/"
            className="inline-flex items-center justify-center font-semibold underline drop-shadow"
          >
            <span>Home</span>
          </Link>
          <Link
            href="/about"
            className="inline-flex items-center justify-center font-semibold underline drop-shadow"
          >
            Projects
          </Link>
          <Link
            href="/about"
            className="inline-flex items-center justify-center font-semibold underline drop-shadow"
          >
            Blog
          </Link>
        </div>
        <div className="grid grid-cols-12 items-center">
          <div className="relative col-span-5 h-screen w-full">
            <Image
              src="/bg-new-left.png"
              alt="Roses as background"
              fill
              style={{ objectFit: "fill" }}
            />
          </div>
          <div className="col-span-4 text-center text-white">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Özgür Sargut
            </h1>
            <div className="w-full text-2xl opacity-75 mt-4">
              FullStack-Developer
            </div>
          </div>
          <div className="relative col-span-3 h-screen w-full">
            <Image
              src="/bg-new-right.png"
              alt="Roses as background"
              fill
              style={{ objectFit: "fill" }}
            />
          </div>
        </div>
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Özgür Sargut
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
        </div> */}
      </main>
    </>
  );
};

export default Home;
